name: Build & Publish (Windows)
on:
push:
    tags:
      - "v0.1.22"
workflow_dispatch:
permissions:
contents: write
jobs:
build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Cache Electron caches (Windows)
        uses: actions/cache@v4
        with:
            ~\AppData\Local\electron\Cache
            ~\AppData\Local\electron-builder\Cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build web assets
        run: npm run build:web
      - name: Build and publish release (electron-builder)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npx electron-builder -w --publish always -c.extraMetadata.main=electron/main.cjs
      - name: Upload dist artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-windows
          path: dist/**
          if-no-files-found: warn
