name: Build & Release App

on:
  push:
    tags:
      - 'v*.*.*'   # only runs when you push a version tag like v0.1.12
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build web bundle
        run: npm run build

      # Package per-OS using the scripts in package.json
      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run pack:win

      - name: Package (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run pack:mac

      - name: Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run pack:linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: dist/**    # electron-builder output folder
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: runner_temp/artifacts

      - name: Create GitHub Release & attach files
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: runner_temp/artifacts/**/*
