name: Build & Release App

on:
  push:
    tags:
      - 'v*.*.*'      # run when you push a version tag
  workflow_dispatch:  # allow manual runs from the Actions tab

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_cmd: npm run build:win
            artifact_glob: "dist/*.{exe,msi}"
          - os: macos-latest
            build_cmd: npm run build:mac
            artifact_glob: "dist/*.{dmg,zip,pkg}"
          - os: ubuntu-latest
            build_cmd: npm run build:linux
            artifact_glob: "dist/*.{AppImage,deb,rpm,tar.gz}"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: ${{ matrix.build_cmd }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-installer
          path: ${{ matrix.artifact_glob }}
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
